# ------------------------------------------------------------
# Copyright (c) Microsoft Corporation and Dapr Contributors.
# Licensed under the MIT License.
# ------------------------------------------------------------

FROM codemonkeyleet/dapr-dev:0.1.2

COPY init-gopath.sh /usr/local/etc/vscode-dev-containers/dapr-dev-scripts/
